---
- name: Verify SNMP
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Show run include SNMP
      cli_command:
        command: show run | inc snmp
      register: command_output

    - name: PRINT TO TERMINAL WINDOW
      debug:
        msg: "{{command_output.stdout}}"
