---
- name: GATHER SNMP FROM ROUTERS
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:

    - name: DISPLAY VERSION
      debug:
        msg: "The SNMP String is: {{ ansible_net_version }}"
